name: Test

on:
  push:
    tags:
      - 'v*'

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            let refs = context.payload.ref.split('/')
            let versionText = refs[refs.length-1].substring(1)
            github.rest.issues.createxxx({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: 'repo-merge-example-bar',
              title: 'ci: promote version ' + versionText,
              assignees: ['matrixji'],
              body: '### Devlake New Version\n\n' + versionText
            })

