name: Test

on:
  push:
    tags:
      - 'v*'

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            console.log(context)
            github.rest.issues.post({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: 'repo-merge-example-bar',
              title: '',
              assignees: ['matrixji'],
              body: ''
            })

